spring.application.name=jobtracker
jwt.secret=super-long-256-bit-secret-key-goes-here-change-this


spring.jpa.properties.hibernate.default_schema=public

spring.liquibase.enabled=true
spring.liquibase.defaultSchema=public
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml


# #mvn-liquibase
changeLogFile=src/main/resources/db/changelog/changelog-master.xml
url=jdbc:postgresql://localhost:5432/postgres
username=postgres
password=artem27danya25
driver=org.postgresql.Driver